### ISSUE TITLE
Anonymization not returning data

### ISSUE THREAD

**Issue by dieriver** [clarus-proxy/anonymization-module#3]
We have tested the integration of the anonymization module and it seems it does not work properly.

We tried a policy (see anon-not.xml) and a transactional query (see query.txt) and the module do not protect the data. When the proxy calls the post module, the "anonymize" function returns null, which results in the failure of the transaction.

[anon-not.xml.txt](https://github.com/clarus-proxy/anonymization-module/files/1418904/anon-not.xml.txt)
[query.txt](https://github.com/clarus-proxy/anonymization-module/files/1418905/query.txt)

**Comment by dieriver** [comment]
It seems the protection method specified in the security policy is not supported by the anonymization module. The policy specifies to protect all the identifiers (pat_id, pat_name, pat_last1 and pat_last2) with "suppresion" protection. This methodology is not implemented in Functions.anonymize function.

**Comment by ablancoj** [comment]
The suppression functionality was tied to the k-anonymization procedure and thus did not work by itself. This has been corrected in commits d54ee784d2b78aae8ea64c4f0b18ab1a05c14afa and d91e152fe31739730578bd61b4cdc36d2b5e3e2c.
